---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: demo4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: hashicorp/http-echo
          args:
            - "-text=Hello from Service A"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: demo4
spec:
  selector:
    app: service-a
  ports:
    - port: 80
      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: demo4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: hashicorp/http-echo
          args:
            - "-text=Hello from Service B"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: demo4
spec:
  selector:
    app: service-b
  ports:
    - port: 80
      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  namespace: demo4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
        - name: service-c
          image: hashicorp/http-echo
          args:
            - "-text=Hello from Service C"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: service-c
  namespace: demo4
spec:
  selector:
    app: service-c
  ports:
    - port: 80
      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d
  namespace: demo4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-d
  template:
    metadata:
      labels:
        app: service-d
    spec:
      containers:
        - name: service-d
          image: hashicorp/http-echo
          args:
            - "-text=Hello from Service D"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: service-d
  namespace: demo4
spec:
  selector:
    app: service-d
  ports:
    - port: 80
      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: demo4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: curlimages/curl
          command: ["sh", "-c"]
          args:
            - |
              while true; do
                echo "--- Calling services ---";
                curl -s http://service-a.demo4.svc.cluster.local;
                curl -s http://service-b.demo4.svc.cluster.local;
                curl -s http://service-c.demo4.svc.cluster.local;
                curl -s http://service-d.demo4.svc.cluster.local;
                sleep 10;
              done
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: demo4
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080
